CREATE TABLE USER 
(
    ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(30) NOT NULL,
    LASTNAME VARCHAR(30) NOT NULL,
    LOGIN VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL
);

INSERT INTO USER VALUES (1, 'KISHOJ', 'BAJRACHARYA', 'KISH', 'kishoj@gmail.com');
